package com.tomtom.navui.input.intent;

import android.content.Intent;

import com.tomtom.navui.appkit.AppContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;
import static org.mockito.Mockito.mock;

@RunWith(RobolectricTestRunner.class)
@Config(manifest = "./src/main/AndroidManifest.xml")
public class IntentActionHandlerTest {

    /**
     * We need check if Launch intent is not parsed
     */
    @Test
    public void testShouldRecognizeLaunchIntent() {

        // GIVEN parser and intent which is generated by android when user lunch application from
        // main menu
        final IntentActionHandler iah = new IntentActionHandler(mock(AppContext.class));
        final Intent launchIntent = getLaunchIntent();

        final boolean expected = true; // yes this is Launch intent.
        // WHEN checking
        final boolean Launch = iah.isLaunchIntent(launchIntent);
        // THEN
        assertThat(Launch, is(expected));
    }

    public Intent getLaunchIntent() {
        final Intent launchIntent = new Intent(Intent.ACTION_MAIN);
        launchIntent.addCategory(Intent.CATEGORY_LAUNCHER);
        return launchIntent;
    }

    /**
     * We need check if Launch intent is not parsed
     */
    @Test
    public void testShouldRecognizeLaunchIntentBoundaryConditions() {

        // GIVEN parser and null intent 
        final IntentActionHandler iah = new IntentActionHandler(mock(AppContext.class));
        final Intent launchIntent = null; // BoundaryConditions
        final boolean expected = true; // yes for use null is Launch intent because parser can't do
                                 // nothing with null
        // WHEN checking ..
        final boolean launch = iah.isLaunchIntent(launchIntent);
        // THEN
        assertThat(launch, is(expected));
    }

    /**
     * We need check if launch intent is handled
     */
    @Test
    public void testShouldRecognizeLaunchIntentHandled() {

        // GIVEN parser and intent which is generated by android when user lunch application from
        // main menu
        final IntentActionHandler iah = new IntentActionHandler(mock(AppContext.class));

        Exception ex = null;
        // WHEN checking..
        try {
            iah.handle(null); // here we test boundary condition.
        } catch (final Exception e) {
            ex = e;
        }
        // THEN
        assertThat(ex, is(nullValue()));// We count that application don't get any exceptions
    }
}
